language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: iYrf/ARiPoRI/dxr1F7qNgtMQDm4zfQn0ihMYqyOEvU/9KUqZepGDb6iOqzxh2LJBU5ajIVzbh1Vj+KNIgbjk6ZMzpF242Pzq3/am0FEg12oHTQpXzspiR080D4utORjLxydWDOLHF647nZ+NDppmxjq8g+4tWwsnoHqDAVbaFNa1P9vgwFtXUOZt9VxYzej6vIjASQ58Ve/GmRjzmlOIttQKeIQ3sRvyefJLA0PzWbVgZRTPZVyekbMStzQnbB5TmsrYgHcCaMyGS4CNa+kkN63huZPpHu1PjjNoqf/wqoBwT7enWbRGL60gcI2tIGXmbsUkY4Cz6aNTNC7Wrn4s9S2V8ZVQeLNBPBWj8JMc4BsyWFC5QfyfNeo8Qhm0hnPg6Qynw8cRiE5kFCczAw/K8fWUG73Gr6EvGyFlvqlcgn0sxLfEu1vV117Rew1Mckeps/TQLAwdz8SBQ2UJFbbx1Jnzhvb1z/KQ39gOVNocwXhrJ/mJcTdsHvzHZuQ6hKdVqQh1lcoWgNEb80ftMjNoWuqLCgy5gcG2mTp06pnSt9qe8Fd7lxaB9DQlmJGEHDBCZ2XWsKLcDWxqE2l0s1PXZgft6X8gMs69KBQHVNAGgGHWFRVMNs4RmscTx20TzHaiF6Xg588loXhcE5QVSKRLCGMgKmdFLDRBAh55RuxTl4=
  app: intense-lowlands-11854
  on:
    repo: alexjc1107/react-trello-testing
